# development:
#   host: dev.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# staging:
#   host: staging.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# production:
#   host: www.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
#   # ssl: true

local:
  host: http://localhost:3000
  handle: logic-optimum
  email: orbanbotond@gmail.com
  api_key: fed9ce79ce62a870d197aa34d115b517ea748208